/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "BankSimulation",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BankSimulation__factory>;
    getContractFactory(
      name: "IBankSimulation",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBankSimulation__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IUniswap",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswap__factory>;

    getContractAt(
      name: "BankSimulation",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BankSimulation>;
    getContractAt(
      name: "IBankSimulation",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IBankSimulation>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IUniswap",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswap>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
