/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as banksimulationSol from "./Banksimulation.sol";
export type { banksimulationSol };
import type * as uniswapSol from "./Uniswap.sol";
export type { uniswapSol };
export type { IBankSimulation } from "./IBankSimulation";
export type { IERC20 } from "./IERC20";
export * as factories from "./factories";
export type { BankSimulation } from "./Banksimulation.sol/BankSimulation";
export { BankSimulation__factory } from "./factories/Banksimulation.sol/BankSimulation__factory";
export { IBankSimulation__factory } from "./factories/IBankSimulation__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export type { IUniswap } from "./Uniswap.sol/IUniswap";
export { IUniswap__factory } from "./factories/Uniswap.sol/IUniswap__factory";
